- name: ensure {{ app_name }} gemset
  command: 'rvm gemset create {{ app_name }}'

- name: ensure {{ app_name }} gems
  command: 'rvm {{ ruby_version}}@{{ app_name }} do bundle install'
  args:
    chdir: '{{ apps_dir }}/{{ app_name }}'
