- name: check {{ app_name }} gemset
  command: rvm gemset create {{ app_name }}
  args:
    chdir: '{{ app_dir }}'

- name: install {{ app_name }} gems
  command: 'rvm {{ ruby_version }}@{{ app_name }} do bundle install'
  args:
    chdir: '{{ app_dir }}'

- name: ensure {{ app_name }} data dir in {{ data_dir }}
  file:
    path: '{{ data_dir }}'
    state: directory

- name: ensure {{ app_name }} log file in {{ logs_file }}
  file:
    path: '{{ logs_file }}'
    state: touch

- name: whenever crontab update
  command: 'rvm {{ ruby_version }}@{{ app_name }} do whenever --update-crontab'
  args:
    chdir: '{{ app_dir }}'
  environment:
    CRAWLERS_DIR: '{{ app_dir }}'
    CRAWLERS_RUBY_GEMSET: '{{ app_name }}'
    CRAWLERS_DATA_DIR: '{{ data_dir }}'
    CRAWLERS_LOG_FILE: '{{ logs_file }}'
    RUBY_VERSION: '{{ ruby_version }}'
