- name: check {{ app_name }} gemset
  command: rvm gemset create {{ app_name }}

- name: install {{ app_name }} gems
  command: 'rvm {{ ruby_version}}@{{ app_name }} do bundle install'
  args:
    chdir: '{{ apps_dir }}/{{ app_name }}'

- name: whenever crontab update
  command: 'rvm {{ ruby_version}}@{{ app_name}} do whenever --update-crontab'
  args:
    chdir: '{{ apps_dir }}/{{ app_name }}'
  environment:
    CRAWLERS_DIR: '{{ apps_dir }}/{{ app_name }}'
    CRAWLERS_RUBY_GEMSET: '{{ app_name }}'
    CRAWLERS_DATA_DIR: '{{ data_dir }}'
    CRAWLERS_LOG_FILE: '{{ logs_dir }}/{{ app_name }}.log'

- name: create {{ app_name }} data dir
  file:
    path: '{{ data_dir }}'
    state: directory

- name: ensure {{ app_name }} logs dir
  file:
    path: '{{ logs_dir }}'
    state: directory
