---
- hosts: iceland
  remote_user: app

  vars:
    # rvm compatible ruby version
    ruby_version: ruby-2.6.3
    rvm_dir: /usr/local/rvm
    rvm_bin: '{{ rvm_dir }}/bin'
    github: https://github.com/spetex/
    apps_dir: /var/www
    apps_log_dir: /var/log/apps
    apps_storage_dir: /var/cache/apps
    local_static_dir: /home/spetex/Repos/Personal/static

  environment:
    PATH: '{{ rvm_bin }}:{{ ansible_env.PATH }}'

  # Common tasks for all roles
  roles:
    - system
    - site
    - static
    - blog
    - rss-feeds
    - web-crawlers
