---
- hosts: iceland
  remote_user: app

  vars:
    ruby_version: ruby
    rvm_dir: /usr/local/rvm/bin
    github: https://github.com/spetex/
    apps_dir: /var/www
    apps_log_dir: /var/log/apps
    apps_storage_dir: /var/cache/apps

  environment:
    PATH: '{{ rvm_dir }}:{{ ansible_env.PATH }}'

  roles:
    - site
    - blog
    - rss-feeds
    - web-crawlers

  # Common handlers for all roles
  handlers:
  - name: ensure nginx restarted
    systemd:
      name: nginx
      state: restarted
    become: yes

  - name: ensure cronie restarted
    systemd:
      name: cronie
      state: restarted
    become: yes
