- name: ensure {{ app_name }} repo
  git:
    repo: '{{ github }}{{ app_name }}.git'
    dest: '{{ app_dir }}'
    update: yes
    clone: yes
    version: master
  notify:
    - check {{ app_name}} gemset
    - install {{ app_name }} gems
    - whenever crontab update
    - ensure {{ app_name }} data dir in {{ data_dir }}
    - ensure {{ app_name }} log file in {{ logs_file }}
    - ensure cronie restarted

- name: ensure {{ app_name }} .ruby-version file
  template:
    src: ../../templates/ruby-version.j2
    dest: '{{ apps_dir}}/{{ app_name }}/.ruby-version'
  notify:
    - check {{ app_name}} gemset
    - install {{ app_name }} gems
    - whenever crontab update
