- name: ensure {{ app_name }} repo
  git:
    repo: '{{ github }}{{ app_name }}.git'
    dest: '{{ apps_dir}}/{{ app_name }}'
    update: yes
    clone: yes
    version: master
  notify:
    - check {{ app_name}} gemset
    - install {{ app_name }} gems
    - whenever crontab update
    - ensure {{ app_name }} data dir in {{ data_dir }}
    - ensure {{ app_name }} logs dir in {{ logs_dir }}
    - ensure cronie restarted
