- name: get ruby version
  command: 'rvm list'
  register: current_version

- name: install {{ ruby_version }}
  command: 'rvm install {{ ruby_version }}'
  when: current_version.stdout.find(ruby_version) == -1
    
- name: ensure bundler gem
  command: 'rvm {{ ruby_version }}@global do gem install bundler:{{ bundler_version }}'

- name: ensure correct nginx.conf in /etc/nginx
  template:
    src: ./templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - ensure nginx restarted

- name: ensure nginx pass file in /etc/nginx
  template:
    src: ./templates/pass.j2
    dest: /etc/nginx/pass
    owner: nginx
    group: nginx
    mode: '0700'
  become: yes
  notify:
    - ensure nginx restarted
