- name: ensure {{ app_name }} repo
  git:
    repo: '{{ github }}{{ app_name }}.git'
    dest: '{{ app_dir }}'
    update: yes
    clone: yes
    version: master
  notify:
    - ensure {{ app_name }} gemset
    - ensure {{ app_name }} gems
    - ensure nginx restarted

- name: ensure {{ app_name }} nginx config in sites-available
  template:
    src: ./templates/nginx.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - ensure nginx restarted

- name: ensure {{ app_name }} nginx symbolic link in sites-enabled
  file:
    src: '/etc/nginx/sites-available/{{ app_name }}'
    dest: '/etc/nginx/sites-enabled/{{ app_name }}'
    state: link
  become: yes
  notify:
    - ensure nginx restarted

- name: ensure {{ app_name }} .ruby-version file
  template:
    src: ../../templates/ruby-version.j2
    dest: '{{ apps_dir}}/{{ app_name }}/.ruby-version'
  notify:
    - ensure {{ app_name }} gemset
    - ensure {{ app_name }} gems
