nginx_log_dir: '/var/log/nginx'
nginx_access_log_file: 'access.log'
nginx_error_log_file: 'error.log'
nginx_passenger_log_file: 'passenger.log'
passenger_src: '/usr/src/passenger-6.0.4'

report_uri_domain: 'https://spetex.report-uri.com'
csp_policies:
  - default-src     'none';
  - form-action     'none';
  - frame-ancestors 'none';
  - connect-src     'self';
  - img-src         'self' static.spetex.cz;
  - style-src       'self' static.spetex.cz fonts.googleapis.com;
  - font-src        'self' static.spetex.cz fonts.gstatic.com;
  - report-uri {{ report_uri_domain }}/r/d/csp/enforce

allowed_origins:
  - spetex.cz
  - spetex.dev
  - petesahula.cz
  - spetex-minis.com
