- name: ensure {{ app_name }} gemset
  command: 'rvm gemset create {{ app_name }}'

- name: ensure {{ app_name }} gem bundler2
  command: 'rvm {{ ruby_version }}@{{ app_name }} do gem install bundler'

- name: ensure {{ app_name }} gems
  command: 'rvm {{ ruby_version }}@{{ app_name }} do bundle install'
  args:
    chdir: '{{ app_dir }}'

- name: ensure jekyll build
  command: 'rvm {{ ruby_version }}@{{ app_name }} do jekyll build'
  args:
    chdir: '{{ app_dir }}'
